import Head from "next/head";
import { useEffect, Fragment } from "react";
import { useDispatch } from "react-redux";
import { addFirstData } from "../components/redux/data";

import { Box } from "@mui/material";
import Calendar from "../components/Calendar";

export default function Home() {
  // ===== Redux ======//
  const dispatch = useDispatch();

  // ===== useEffect ======//
  useEffect(() => {
    const data = localStorage.getItem("data");
    if (data && data.length > 0) {
      dispatch(addFirstData(JSON.parse(data)));
    }
  }, []);
  return (
    <Fragment>
      <Head>
        <title>Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box textAlign="center">
        <Calendar />
      </Box>
    </Fragment>
  );
}
